# Generated by Django 5.1.1 on 2024-12-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('hora_que_reserva', models.CharField(max_length=50)),
                ('hora_salida', models.CharField(max_length=50)),
            ],
        ),
    ]
