# Generated by Django 5.1.1 on 2024-12-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('hora_llegada', models.CharField(max_length=50)),
            ],
        ),
    ]
