# Generated by Django 5.1.1 on 2024-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id_tienda', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.PositiveIntegerField()),
                ('correo_electronico', models.EmailField(max_length=50)),
                ('horario', models.CharField(max_length=100)),
                ('tipo_de_productos', models.CharField(max_length=50)),
            ],
        ),
    ]
