# Generated by Django 5.1.1 on 2024-12-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.PositiveIntegerField()),
                ('fecha_reserva', models.DateField()),
                ('numero_reserva', models.PositiveBigIntegerField()),
                ('hora_llegada', models.CharField(max_length=100)),
                ('hora_salida', models.CharField(max_length=100)),
                ('id_mesa', models.PositiveIntegerField()),
            ],
        ),
    ]
